### PR TITLE
Add WinPwn to Windows tools

### PR DESCRIPTION
**Pull request by Karmhack**
Add WinPwn to Windows tools : 
- 2 files : WinPwn.exe and WinPwn.ps1

### CODE REVIEW

**Review by ShutdownRepo — CHANGES_REQUESTED** [review]
Thank you for the pull request. However, can you please modify the [update-resources.sh](https://github.com/ThePorgs/Exegol-resources/blob/main/update-resources.sh) script instead? so that the resources are dynamically installed and updated

**Comment by Karmhack** [comment]
> Thank you for the pull request. However, can you please modify the [update-resources.sh](https://github.com/ThePorgs/Exegol-resources/blob/main/update-resources.sh) script instead? so that the resources are dynamically installed and updated

Of course, I deleted this directory and make another PR once i edited update-resources.sh.

**Review by ShutdownRepo — APPROVED** [review]

**Comment by Dramelac** [comment]
What is missing here for merge ?

**Review by ShutdownRepo — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
> What is missing here for merge ?

Time. Time was missing 😅 
I think we're good to go, LGTM

**Pull request merged**
